/**
 * Renders its children inside a hidden print-only block. When the user clicks
 * "Print", a clean A4 page is what reaches the printer / PDF — without the
 * sidebar / topbar / dark theme.
 */
export default function PrintLayout({ title, meta, children }) {
  return (
    <div className="print-only print-page">
      <h1 style={{ fontSize: '20pt', marginBottom: '8mm' }}>{title}</h1>
      {meta && (
        <div className="meta" style={{ fontSize: '10pt', color: '#444' }}>
          {meta}
        </div>
      )}
      {children}
      <div style={{ marginTop: '12mm', fontSize: '9pt', color: '#666' }}>
        Generated by Nyaya AI — Educational use only. Not legal advice.
      </div>
    </div>
  )
}
